### ISSUE TITLE
LED Display Flashing "Loading" Net Image After Fresh Install

### ISSUE THREAD

**Issue by ramsaytc** [falkyre/nhl-led-scoreboard-img#1]
On a fresh install: setting one preferred team and answering all of the questions during initial setup (size of board, etc), the LED display is stuck in a loop, flashing the "Loading" screen.

See pastebin for config.json: [https://pastebin.com/fM0kQVdn](https://pastebin.com/fM0kQVdn)

**Comment by ramsaytc** [comment]
Pastebin of sb-stderr:  [https://pastebin.com/mJtPw2fr](https://pastebin.com/mJtPw2fr)

**Comment by falkyre** [comment]
ssh to the raspberry pi.  Run `sb-stop` then try this `sudo pip3 install certifi`.  The run `sb-start` and see if your board runs.

**Comment by ramsaytc** [comment]
> ssh to the raspberry pi. Run `sb-stop` then try this `sudo pip3 install certifi`. The run `sb-start` and see if your board runs.

Done.  Board is still looping. This was the output after `sudo pip3 install certifi`

`Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (2018.8.24)`

**Comment by falkyre** [comment]
Try `sudo pip3 install certifi --upgrade`

**Comment by ramsaytc** [comment]
That upgraded it to certifi-2020.12.5, however the board still runs in a loop.

Updated stderr:  [https://pastebin.com/5MncUh78](url)

**Comment by riffnshred** [comment]
those `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)` is cause by the nhl server where we get the logos right ?

**Comment by riffnshred** [comment]
@falkyre I found something on the nhl-led-scoreboard side. the damn `firstrun` file does not exist in the release. not sure if that is related but definitely will prevent the scoreboard from working. I just pushed a fix, let me know if that fix this issue at the same time.

**Comment by falkyre** [comment]
> those `ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)` is cause by the nhl server where we get the logos right ?

Sort of yes.  It's the requests library that we are using to pull that's spitting that out.  The fix is supposed to be upgraded the certifi library. But that appears to have not worked. I am just getting a board setup with the image today so I can test it and see what's going on

**Comment by falkyre** [comment]
> @falkyre I found something on the nhl-led-scoreboard side. the damn `firstrun` file does not exist in the release. not sure if that is related but definitely will prevent the scoreboard from working. I just pushed a fix, let me know if that fix this issue at the same time.
> 
> 

First run file is more for the config.json.  Shouldn't impact the image downloads.

**Comment by falkyre** [comment]
It was a bad build of the image.  I redid it locally and tried it out and it works fine.  The new image has been uploaded.  Try it out and let me know if it works for you and I'll close this issue

**Comment by ramsaytc** [comment]
I redid my board with the updated image.  It worked for about an hour, and now is stuck in the loading loop again.  Is there a sleep command after X minutes?

Pastebin with sb-stderr log:  [https://pastebin.com/X6Ld8q8H](https://pastebin.com/X6Ld8q8H)

**Comment by falkyre** [comment]
OK, I'm going to close this as the error you are seeing above is core to the code and not part of the image.  Open another issue @ https://github.com/riffnshred/nhl-led-scoreboard/issues
